#!/bin/bash
#
# SCRIPT: try3
# AUTHOR: Shivani Mehrotra
# DATE:   26/03/2020
# REV:    1.1.A (Valid are A, B, D, T and P)
#          (For Alpha, Beta, Dev, Test and Production)
#
#
# PLATFORM: Ubuntu
# 
# PURPOSE: To find memory consumption information through awk.
# REV LIST:
#    DATE        : Date of revision
#    BY          : AUTHOR OF MODIFICATION
#    MODIFICATION: Describe the chages made. What do they enhance.
# 
# set -n   # Uncomment to check script syntax, without execution.
#          # NOTE: Do forget comment it back as it won't allow the 
#          # the script to execute.
#
set +x   # Uncomment this for debugging this shell script.
#
#
################################################################
#          Define Files and Variables here                     #
################################################################

fileName="/proc/meminfo"

################################################################
#          Define Functions here                               #
################################################################

print_memory_info(){
	awk '/MemTotal/{print}' $fileName
	awk '/MemFree/{print}' $fileName
	awk '/MemAvailable/{print}' $fileName
	awk '/Buffers/{print}' $fileName
	awk '/^Cached/{print}' $fileName
}

################################################################
#          Beginning of Main                                   #
################################################################

print_memory_info

# End of script
